import React,{useState,useEffect} from 'react'
import {getUserListManagment} from '../../services/auth'

const UserManagmentList = ({onBackClick}) => {
   const [users,setUsers]=useState([]);
   const [loading,setLoading]=useState(true)

   useEffect(()=>{
     getUserListManagment()
  .then(data=>{
    setUsers(data.users || []);
    setLoading(false)
  })
  .catch(err=>{
    setLoading(false)
  })

   },[])
   if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center font-bold text-sm text-slate-500 min-h-screen">
        Loading Users Registry Data...
      </div>
    );
  }
  return (
    <div className="p-4 md:p-8 bg-slate-50 min-h-screen font-sans">
        <div className="max-w-5xl mx-auto bg-white border border-slate-200 shadow-sm rounded-2xl p-6">
            <div className="flex items-center justify-between mb-6">
                <div>
            <h2 className="text-base font-bold text-slate-800 tracking-tight uppercase">Admin Console</h2>
            <p className="text-xs text-slate-400 font-medium">Viewing credentials generated by the Admin.</p>
          </div>
          <button
          onClick={onBackClick}
          className="text-xs font-bold text-slate-600 hover:text-slate-900 border border-slate-300 px-3 py-1.5 rounded-lg hover:bg-slate-50 transition cursor-pointer"
          
          >
            ← Back to Board
          </button>

            </div>
     

     {/* desktop view  */}
            <div  className="hidden md:block overflow-x-auto rounded-xl border border-slate-200">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-slate-50 border-b border-slate-200 text-[10px] font-bold text-slate-400 uppercase tracking-wider">
                           <th className="py-3 px-4">User Name</th>
                            <th className="py-3 px-4">Email</th>
                           
                            <th className="py-3 px-4">Access Role</th> 


                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 text-xs text-slate-600 font-medium">
                        {users.length===0?(
                            <tr>
                  <td colSpan="4" className="text-center py-6 text-slate-400">No users found.</td>
                </tr>
                        ):(
                            users.map(user=>(
                                <tr key={user.id  || user._id} className="hover:bg-slate-50/50 transition">
                                    <td className="py-3.5 px-4 font-bold text-slate-700">{user.name}</td>
                                    <td className="py-3.5 px-4 text-slate-500">{user.email}</td>
                                    <td className="py-3.5 px-4">
                      <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${user.role === 'ADMIN' ? 'bg-purple-50 text-purple-600' : 'bg-blue-50 text-blue-600'}`}>
                        {user.role}
                      </span>
                    </td>
                                </tr>
                                
                            ))
                        )}

                    </tbody>

                </table>

            </div>

            {/*mobile view card*/}
            <div className="block md:hidden space-y-3">
                {users.length ===0 ?(

                     <div className="text-center py-8 text-xs text-slate-400 border border-dashed border-slate-200 rounded-xl">
              No registered users found in system logs.
            </div>
                ):(
                    users.map(user=>(
                        <div key={user.id || user._id}  className="bg-white border border-slate-200 p-4 rounded-xl shadow-sm flex flex-col gap-2">
                            <div className="flex items-center justify-between gap-2">
                                 <span className="text-xs font-bold text-slate-800 truncate">{user.name}</span>
                                <span className={`px-2 py-0.5 shrink-0 rounded-full text-[9px] font-bold tracking-wide uppercase ${user.role === 'ADMIN' ? 'bg-purple-50 text-purple-600 border border-purple-100' : 'bg-blue-50 text-blue-600 border border-blue-100'}`}>
                                    {user.role}
                                </span>
                            </div>
                             <div className="text-[11px] text-slate-400 font-medium break-all">
                            <span className="text-slate-500 font-semibold">Email:</span> {user.email}
                            </div>

                        </div>
                    ))
                )}



            </div>

        </div>
      
    </div>
  )
}

export default UserManagmentList
